// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"forgetting-curve/backend/internal/biz"
	"forgetting-curve/backend/internal/conf"
	"forgetting-curve/backend/internal/data"
	"forgetting-curve/backend/internal/server"
	"forgetting-curve/backend/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	studentRepo := data.NewStudentRepo(dataData)
	studentUsecase := biz.NewStudentUsecase(studentRepo, logger)
	wordRepo := data.NewWordRepo(dataData)
	wordUsecase := biz.NewWordUsecase(wordRepo, studentRepo, logger)
	studentService := service.NewStudentService(studentUsecase, wordUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, studentService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
