// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"forgetting-curve/backend/internal/biz"
	"forgetting-curve/backend/internal/conf"
	"forgetting-curve/backend/internal/data"
	"forgetting-curve/backend/internal/server"
	"forgetting-curve/backend/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, wechat *conf.Wechat, ocr *conf.OCR, llm *conf.LLM, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	studentRepo := data.NewStudentRepo(dataData)
	studentUsecase := biz.NewStudentUsecase(studentRepo, logger)
	wordRepo := data.NewWordRepo(dataData)
	planRepo := data.NewPlanRepo(dataData)
	llmService := biz.NewLLMService(llm, logger)
	wordUsecase := biz.NewWordUsecase(wordRepo, planRepo, studentRepo, llmService, logger)
	confusedWordRepo := data.NewConfusedWordRepo(dataData)
	confusedWordUsecase := biz.NewConfusedWordUsecase(confusedWordRepo, wordRepo, planRepo, studentRepo, logger)
	planUsecase := biz.NewPlanUsecase(planRepo, wordRepo, studentRepo, logger)
	wechatService := biz.NewWechatService(wechat, logger)
	ocrService := data.NewUmiOCRClient()
	pronunciationService := biz.NewPronunciationService(logger)
	studentService := service.NewStudentService(studentUsecase, wordUsecase, confusedWordUsecase, planUsecase, wechatService, ocrService, pronunciationService, logger)
	httpServer := server.NewHTTPServer(confServer, studentService, ocrService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
